sudo: required
cache:
  - apt
language: generic

# ros distro
matrix:
  include:
    - name: "Bionic melodic"
      dist: bionic
      env: ROS_DISTRO=melodic

branches:
  only:
    - master

# env
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt update
  - sudo apt install -y ros-$ROS_DISTRO-desktop-full python-rosdep python-catkin-pkg python-wstool python-catkin-tools
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - sudo rosdep init
  - rosdep update
  - git clone https://github.com/openspur/yp-spur
  - cd yp-spur
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig

install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  - catkin init
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

script:
  - cd ~/catkin_ws
  - catkin build
