scan_filter_chain:
- type: laser_filters/LaserArrayFilter
  name: laser_median_filter
  params:
    range_filter_chain:
      - name: median
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 10
          unused: 10
    intensity_filter_chain:
      - name: median
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 10
          unused: 10