adamr2:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'
    publish_rate: 50

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 10.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 10.0]

    wheel_separation: 0.383
    wheel_radius: 0.0775
    cmd_vel_timeout: 0.5

    base_frame_id: base_footprint
    odom_frame_id: odom

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 0.25
        min_acceleration: -0.25
      
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.785
        min_velocity: -0.785
        has_acceleration_limits: true
        max_acceleration: 0.785
        min_acceleration: -0.785
