local_costmap:
  # Plugins
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # Coordinate frame and tf parameters
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.2  # default: 0.2
  footprint: [[0.35, 0.225], [0.35, -0.225], [-0.37, -0.225], [-0.37, 0.225]]

  #  Rate parameters
  update_frequency: 5.0    # default: 5.0
  publish_frequency: 5.0   # default: 0.0

  # Map management parameters
  rolling_window: true
  always_send_full_costmap: false
  width: 8.0        # default: 10.0
  height: 8.0       # default: 10.0
  resolution: 0.05  # default: 0.05

  # parameters of each plugins
  obstacle_layer:
    observation_sources: laser_scan pointcloud_sensor
    laser_scan:
      topic: /adamr2/scan
      sensor_frame: lidar_link
      observation_persistence: 0.0  # default: 0.0
      expected_update_rate: 0.2     # default: 0.0
      data_type: LaserScan
      clearing: true        # default: false
      marking: true         # default: true
      obstacle_range: 2.5   # default: 2.5
      raytrace_range: 3.0   # default: 3.0
      inf_is_valid: false   # default: false
    pointcloud_sensor:
      topic: /adamr2/camera/depth/color/points
      sensor_frame: camera_depth_frame
      observation_persistence: 0.0  # default: 0.0
      expected_update_rate: 0.1     # default: 0.0
      data_type: PointCloud2
      clearing: true            # default: false
      marking: true             # default: true
      max_obstacle_height: 1.0  # default: 2.0
      min_obstacle_height: 0.1  # default: 0.0
      obstacle_range: 2.5       # default: 2.5
      raytrace_range: 3.0       # default: 3.0
      inf_is_valid: false       # default: false

  inflation_layer:
    inflation_radius: 0.4     # default: 0.55
    cost_scaling_factor: 3.66 # default: 10.0