base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 0.8
  acc_lim_y: 0.0
  #acc_lim_trans: 1.0
  acc_lim_theta: 3.14

  max_vel_trans: 1.0
  min_vel_trans: 0.0
  max_vel_x: 1.0
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.57
  min_vel_theta: 0.0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.050
  vx_samples: 20
  vy_samples: 1
  vth_samples: 40
  #controller_frequency: 10.0

  # Trajectory Scoring Parameters
  path_distance_bias: 64.0
  goal_distance_bias: 24.0
  occdist_scale: 0.02
  forward_point_distance: 1.0
  stop_time_buffer: 0.2
  scaling_speed: 1.2
  max_scaling_factor: 0.2
  publish_cost_grid: true

  # Oscillation Preventation Parameters
  #oscillation_reset_dist: 0.3

  # Global Plan Parameters
  prune_plan: true
