base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 0.75
  acc_lim_y: 0.0
  acc_lim_trans: 0.75
  acc_lim_theta: 3.14

  max_vel_trans: 0.3
  min_vel_trans: 0.1

  max_vel_x: 0.3
  min_vel_x: -0.1
  
  max_vel_y: 0.0
  min_vel_y: 0.0
  
  max_vel_theta: 1.57
  min_vel_theta: 0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.25  # default: 0.1
  xy_goal_tolerance: 0.25   # default: 0.1

  trans_stopped_vel: 0.08   # default: 0.1
  theta_stopped_vel: 0.08   # default: 0.1

  # Forward Simulation Parameters
  sim_time: 4.0                 # default: 1.7
  sim_granularity: 0.050        # default: 0.025
  angular_sim_granularity: 0.1  # default: 0.1
  vx_samples: 20                # default: 3
  vy_samples: 1                 # default: 10
  vth_samples: 40               # default: 20

  # Trajectory Scoring Parameters
  path_distance_bias: 2.0       # default: 0.6
  goal_distance_bias: 0.8       # default: 0.8
  occdist_scale: 0.02           # default: 0.01
  twirling_scale: 0.2           # default: 0.0
  forward_point_distance: 1.0   # default: 0.325
  stop_time_buffer: 0.2         # default: 0.2
  scaling_speed: 0.4            # default: 0.25
  max_scaling_factor: 0.2       # default: 0.2
  publish_cost_grid_pc: true    # default: false
  publish_traj_pc: true         # default: false

  # Oscillation Preventation Parameters
  oscillation_reset_dist: 0.1 # default: 0.05
  oscillation_rest_angle: 0.2 # default: 0.2

  # Global Plan Parameters
  prune_plan: true  # default: false

  # Miscellaneous
  use_dwa: true   # default: true

  restore_defaults: false # default: false