base_local_planner: base_local_planner/TrajectoryPlannerROS
TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: -0.8
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0
  acc_lim_x: 0.8
  acc_lim_theta: 1.0

  holonomic_robot: false

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25