obstacle_range: 2.0
raytrace_range: 6.0
footprint: [[0.225, 0.3], [0.225, -0.3], [-0.225, -0.3], [-0.225, 0.3]]
inflation_radius: 0.5 #1.0
cost_scaling_factor: 0.5 #10
observation_sources: scan
scan: {
  sensor_frame: lidar_link, 
  topic: /scan,
  data_type: LaserScan, 
  expected_update_rate: 1.0,
  observation_persistence: 0.0, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 1.0, 
  min_obstacle_height: -0.15
  }  

transform_tolerance: 0.2
  