global_costmap:
  # Plugins
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  # Coordinate frame and tf parameters
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.2  # default: 0.2
  footprint: [[0.225, 0.3], [0.225, -0.3], [-0.225, -0.3], [-0.225, 0.3]]

  # Rate parameters
  update_frequency: 2.0     # default: 5.0
  publish_frequency: 2.0    # default: 0.0(disable)

  # Map management parameters
  rolling_window: false           # default: false
  always_send_full_costmap: false # default:false

  # parameters of each plugins
  static_layer:
    unknown_cost_value: -1      # default: -1
    lethal_cost_threshold: 100  # default: 100
    map_topic: map              # default: map
    first_map_only: false       # default: false
    subscribe_to_updates: true  # default: false
    track_unknown_space: false  # default: true
    use_maximum: false          # default: false
    trinary_costmap: true       # default: true

  inflation_layer:
    inflation_radius: 0.55      # default: 0.55
    cost_scaling_factor: 10.0   # default: 10.0