min_particles: 30  # default = 100
max_particles: 100 # default = 5000

kld_err: 0.01 # default = 0.01
kld_z: 0.99   # default = 0.99

update_min_d: 0.05 # default = 0.2
update_min_a: 0.05 # default = PI / 6.0 ~= 0.5

resample_interval: 1      #  default = 2
transform_tolerance: 0.1  # default = 0.1
recovery_alpha_slow: 0.0  # default = 0.0
recovery_alpha_fast: 0.0  # default = 0.0

gui_publish_rate: 10.0  # default = -1.0[Hz](disable)

save_pose_rate: 0.5   # defautl = 0.5
use_map_topic: true   # defaut = false
first_map_only: true  # default = falase

laser_min_range: 0.15           # default = -1.0
laser_max_range: 8.0            # default = -1.0
laser_max_beams: 60             # default = 30
laser_z_hit: 0.5                # default = 0.95
laser_z_short: 0.05             # default = 0.1
laser_z_max: 0.05               # default = 0.05
laser_z_rand: 0.5               # default = 0.5
laser_sigma_hit: 0.2            # default = 0.2
laser_lambda_short: 0.1         # default = 0.1
laser_likelihood_max_dist: 2.0  # default = 2.0
laser_model_type: beam          # default = likelihood_filed


odom_model_type: diff-corrected # default = diff
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
#odom_alpha5: 0.2
odom_frame_id: odom # default = odom
base_frame_id: base_footprint # default = base_link
global_frame_id: map # default = map
tf_broadcast: true # default = true
