controller_frequency: 10.0
controller_patience: 15.0

planner_patience: 5.0
planner_frequency: 0.0

conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false

oscillation_timeout: 0.0
oscillation_distance: 0.5

max_planning_retries: -1
