global_costmap:
  # Plugins
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  # Coordinate frame and tf parameters
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.2  # default: 0.2
  footprint: [[0.35, 0.225], [0.35, -0.225], [-0.37, -0.225], [-0.37, 0.225]]

  # Rate parameters
  update_frequency: 2.0     # default: 5.0
  publish_frequency: 2.0    # default: 0.0(disable)

  # Map management parameters
  rolling_window: false           # default: false
  always_send_full_costmap: false # default:false

  # parameters of each plugins
  static_layer:
    unknown_cost_value: -1      # default: -1
    lethal_cost_threshold: 100  # default: 100
    map_topic: map              # default: map
    first_map_only: false       # default: false
    subscribe_to_updates: false # default: false
    track_unknown_space: true   # default: true
    use_maximum: false          # default: false
    trinary_costmap: true       # default: true

  obstacle_layer:
    observation_sources: laser_scan
    laser_scan:
      topic: /adamr2/scan
      sensor_frame: lidar_link
      observation_persistence: 0.0  # default: 0.0
      expected_update_rate: 0.2     # default: 0.0
      data_type: LaserScan
      clearing: true        # default: false
      marking: true         # default: true
      obstacle_range: 2.5   # default: 2.5
      raytrace_range: 3.0   # default: 3.0
      inf_is_valid: true   # default: false

  inflation_layer:
    inflation_radius: 0.8     # default: 0.55
    cost_scaling_factor: 1.74 # default: 10.0