controller_frequency: 5.0  # default: 20.0
controller_patience: 15.0   # default: 15.0

planner_frequency: 1.0  # default: 0.0
planner_patience: 5.0   # default: 5.0

conservative_reset_dist: 3.0    # default: 3.0
recovery_behavior_enabled: true # default: true
clearing_rotation_allowed: true # default: true
shutdown_costmaps: false        # default: false

oscillation_timeout: 5.0    # default: 0.0
oscillation_distance: 0.2   # default: 0.5

max_planning_retries: 10    # default: -1